title: Adnan Haque here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Data Scientist working in life insurance.
  <br><br>
  <a href="https://www.linkedin.com/in/adnan-haque-1512b148/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
